#!/usr/bin/env node

/**
 * Converts an emoji to a base64-encoded SVG favicon
 * Usage: ./emoji-favicon "🦄"
 */

const emoji = process.argv[2];

if (!emoji) {
  console.error('Usage: emoji-favicon "🚀"');
  process.exit(1);
}

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <text y="75" font-size="80">${emoji}</text>
</svg>`;

const base64 = Buffer.from(svg).toString('base64');
const dataUri = `data:image/svg+xml;base64,${base64}`;

console.log(dataUri);
